CREATE TABLE IF NOT EXISTS reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  travel_id INT NOT NULL,
  user_id INT NOT NULL,
  rating TINYINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (travel_id) REFERENCES travels(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE reservations 
  ADD COLUMN payment_status VARCHAR(20) NOT NULL DEFAULT 'Pending',
  ADD COLUMN payment_method VARCHAR(50) NOT NULL DEFAULT 'Transfer',
  ADD COLUMN payment_proof VARCHAR(255) DEFAULT NULL;
